### ISSUE TITLE
bug: Test failure 

### ISSUE THREAD

**Issue by Domejko** [TreyWW/MyFinances#361]
### What version of MyFinances are you currently using?

v0.4.5

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

I have encounter a strange bug. When I run `python manage.py test --parallel` I'm getting dozens of the same error messages:
```command
 AttributeError: 'NoneType' object has no attribute 'reason_phrase'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 145, in response_for_exception
    response.reason_phrase,
    ^^^^^^^^^^^^^^^^^^^^^^
```

or there is also another error message:

```command
test_clients_view_302_for_all_normal_get_requests (tests.api.test_currency_converter.CurrencyConverterConvertAPI.test_clients_view_302_for_all_normal_get_requests) failed:

    AttributeError("'NoneType' object has no attribute 'reason_phrase'")

Unfortunately, the exception it raised cannot be pickled, making it impossible
for the parallel test runner to handle it cleanly.

Here's the error encountered while trying to pickle the exception:

    PicklingError("Can't pickle <function colorize at 0x722966721f80>: it's
    not the same object as
    django_extensions.templatetags.syntax_color.colorize")

You should re-run this test with the --parallel=1 option to reproduce the
failure and get a correct traceback.

WAS A TRACEBACK ERROR: EXCEPTION: None


test_302_for_non_authenticated_users (tests.api.test_account_settings.CurrencyAPIChange.test_302_for_non_authenticated_users) failed:

    AttributeError("'NoneType' object has no attribute 'reason_phrase'")

Unfortunately, the exception it raised cannot be pickled, making it impossible
for the parallel test runner to handle it cleanly.

Here's the error encountered while trying to pickle the exception:

    PicklingError("Can't pickle <function colorize at 0x722966721f80>: it's
    not the same object as
    django_extensions.templatetags.syntax_color.colorize")

You should re-run this test with the --parallel=1 option to reproduce the
failure and get a correct traceback.

Destroying test database for alias 'default'...
Destroying test database for alias 'default'...
Destroying test database for alias 'default'...
Destroying test database for alias 'default'...
Destroying test database for alias 'default'...
Destroying test database for alias 'default'...
Destroying test database for alias 'default'...
Destroying test database for alias 'default'...
Destroying test database for alias 'default'...
Traceback (most recent call last):
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/manage.py", line 21, in <module>
    main()
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/venv/lib/python3.12/site-packages/django/core/management/commands/test.py", line 24, in run_from_argv
    super().run_from_argv(argv)
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/venv/lib/python3.12/site-packages/django/core/management/commands/test.py", line 68, in handle
    failures = test_runner.run_tests(test_labels)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/venv/lib/python3.12/site-packages/django/test/runner.py", line 1068, in run_tests
    result = self.run_suite(suite)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/venv/lib/python3.12/site-packages/django/test/runner.py", line 995, in run_suite
    return runner.run(suite)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/runner.py", line 240, in run
    test(result)
  File "/usr/lib/python3.12/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/domejko/Documents/Contribution_Projects/MyFinances/venv/lib/python3.12/site-packages/django/test/runner.py", line 541, in run
    subsuite_index, events = test_results.next(timeout=0.1)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 873, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x72296518c2f0>'. Reason: 'PicklingError("Can't pickle <function colorize at 0x722966721f80>: it's not the same object as django_extensions.templatetags.syntax_color.colorize")'
```

They are interchanging.

I have encounter this also yesterday when I was merging `main` branch to my forked `main`. Then also test failed 2 times. And first error message then was:
```command
#14 16.07   IncompleteRead
#14 16.07 
#14 16.07   IncompleteRead(4194304 bytes read, 2102863 more expected)
#14 16.07 
#14 16.07   at /usr/local/lib/python3.12/site-packages/urllib3/response.py:883 in _raw_read
#14 16.09        879│                     # to concerns of backward compatibility. We're
#14 16.09        880│                     # addressing it here to make sure IncompleteRead is
#14 16.09        881│                     # raised during streaming, so all calls with incorrect
#14 16.09        882│                     # Content-Length are caught.
#14 16.09     →  883│                     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
#14 16.09        884│             elif read1 and (
#14 16.09        885│                 (amt != 0 and not data) or self.length_remaining == len(data)
#14 16.09        886│             ):
#14 16.09        887│                 # All data has been read, but `self._fp.read1` in
#14 16.09 
#14 16.09 The following error occurred when trying to handle this error:
#14 16.09 
#14 16.09 
#14 16.09   ProtocolError
#14 16.09 
#14 16.09   ('Connection broken: IncompleteRead(4194304 bytes read, 2102863 more expected)', IncompleteRead(4194304 bytes read, 2102863 more expected))
#14 16.09 
#14 16.09   at /usr/local/lib/python3.12/site-packages/urllib3/response.py:761 in _error_catcher
#14 16.11        757│                 ):
#14 16.11        758│                     arg = "Response may not contain content."
#14 16.11        759│                 else:
#14 16.11        760│                     arg = f"Connection broken: {e!r}"
#14 16.11     →  761│                 raise ProtocolError(arg, e) from e
#14 16.11        762│ 
#14 16.11        763│             except (HTTPException, OSError) as e:
#14 16.11        764│                 raise ProtocolError(f"Connection broken: {e!r}", e) from e
#14 16.11        765│ 
#14 16.11 
#14 16.11 The following error occurred when trying to handle this error:
#14 16.11 
#14 16.11 
#14 16.11   ChunkedEncodingError
#14 16.11 
#14 16.11   ('Connection broken: IncompleteRead(4194304 bytes read, 2102863 more expected)', IncompleteRead(4194304 bytes read, 2102863 more expected))
#14 16.11 
#14 16.11   at /usr/local/lib/python3.12/site-packages/requests/models.py:818 in generate
#14 16.12        814│             if hasattr(self.raw, "stream"):
#14 16.12        815│                 try:
#14 16.12        816│                     yield from self.raw.stream(chunk_size, decode_content=True)
#14 16.12        817│                 except ProtocolError as e:
#14 16.12     →  818│                     raise ChunkedEncodingError(e)
#14 16.12        819│                 except DecodeError as e:
#14 16.12        820│                     raise ContentDecodingError(e)
#14 16.12        821│                 except ReadTimeoutError as e:
#14 16.12        822│                     raise ConnectionError(e)
#14 16.12 
#14 16.12 Cannot install typos.
#14 16.12 
#14 ERROR: process "/bin/sh -c poetry install --without dev,mysql,postgres --no-root && rm -rf $POETRY_CACHE_DIR" did not complete successfully: exit code: 1
------
 > [myfinances_django  9/12] RUN poetry install --without dev,mysql,postgres --no-root && rm -rf /tmp/poetry_cache:
failed to solve: process "/bin/sh -c poetry install --without dev,mysql,postgres --no-root && rm -rf $POETRY_CACHE_DIR" did not complete successfully: exit code: 1
16.12        816│                     yield from self.raw.stream(chunk_size, decode_content=True)
16.12        817│                 except ProtocolError as e:
16.12     →  818│                     raise ChunkedEncodingError(e)
16.12        819│                 except DecodeError as e:
16.12        820│                     raise ContentDecodingError(e)
16.12        821│                 except ReadTimeoutError as e:
16.12        822│                     raise ConnectionError(e)
16.12 
16.12 Cannot install typos.
```
After that I have run it for the second time with debug mode and it give me this message again mentioning Django `colorize`:
```command
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7fdbca684740>'. Reason: 'PicklingError("Can't pickle <function colorize at 0x7fdbccd20d60>: it's not the same object as django_extensions.templatetags.syntax_color.colorize")'
```
At 3rd run it have passed the test.

Strange thing is that when on my desktop I run test with additional `--debug-mode` flag like this `python manage.py test --parallel --debug-mode` it's passing all test with out any errors at every single time that I run tests.
I'm working on Ubuntu same as github container.

**Comment by Domejko** [comment]
@TreyWW do you also get those errors on Windows now or it happens only on Linux ?

**Comment by Domejko** [comment]
Yes and it's strange that when I run it with `--debug-mode` flag it runs without any issues but when I run it without it on my Ubuntu 22.04 it fails all the time, Tomorrow I'll update my os to current LTS 24.04 and we'll see if the same thing will be happening. Github actions is still running on 22.04 but I think soon they will provide 24.04 since it just got released. If on 24.04 everything will be fine then it will be just a temporary issue.

**Comment by Domejko** [comment]
I did update my Ubuntu to 24.04 and errors where still occurring but I have discovered few things.

- At first when I run test with `--parallel --debug-mode` flags it have failed this time **but** it give me a message that it needs `webpack-stats.json`  since some tests demanded it:
```command
test_302_for_all_normal_get_requests (tests.api.test_invoices.InvoicesAPIDelete.test_302_for_all_normal_get_requests) failed:

    OSError('Error reading
    /home/domejko/Documents/Contribution_Projects/MyFinances/webpack-
    stats.json. Are you sure webpack has generated the file and the path is
    correct?')

Unfortunately, the exception it raised cannot be pickled, making it impossible
for the parallel test runner to handle it cleanly.

Here's the error encountered while trying to pickle the exception:

    PicklingError("Can't pickle <function colorize at 0x717e20c1e0c0>: it's
    not the same object as
    django_extensions.templatetags.syntax_color.colorize")
```
I did run `npm run webpack-dev` and `webpack-stats.json` have been created. Now when I run tests with `--parallel` flag they are still failing but when I use `--parallel --debug-mode` all test are passing like on old kernel.

When running test with `--parallel=1` flag almost all errors seams to have it's origin in lack of response from request API
```command
get_response(request)
```
which result with:
```command
AttributeError: 'NoneType' object has no attribute 'reason_phrase'
```

I assume that tests with `--debug-mode` are passing since Django automatically enables then additional middleware `DebugToolbarMiddleware` .

**Comment by TreyWW** [comment]
Django logs are pretty rubbish, you have to go right to the top to see any helpful logs
